#ifndef LIBTHECALCULATOR_GLOBAL_H
#define LIBTHECALCULATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBTHECALCULATOR_LIBRARY)
    #define LIBTHECALCULATOR_EXPORT Q_DECL_EXPORT
#else
    #define LIBTHECALCULATOR_EXPORT Q_DECL_IMPORT
#endif

#define LIBTHECALCULATOR_TRANSLATOR "thecalculator/libthecalculator"

#endif // LIBTHECALCULATOR_GLOBAL_H
